### PR TITLE
LinkedList Implementation and some problems

### PR DESCRIPTION
**Pull request by Anurag127001**
LinkedList Implementation and some problems like find loop if exists and remove it are added in DSA folder as mentioned in issue #1

### CODE REVIEW

**Comment by indrakishore** [comment]
Hi, Anurag
Please follow protocol and rename your file as LinkedListImplementaionByAnurag.java

**Comment by Anurag127001** [comment]
> Hi, Anurag Please follow protocol and rename your file as LinkedListImplementaionByAnurag.java

I have renamed it, could you please merge it to main if everything's right, if not please let me know necessary changes

**Comment by indrakishore** [comment]
@Anurag127001 It appears that you are pushing more files, which is not a good practice for adding to a repository. You can add those files in .gitignore causes git to ignore those files. Simply push LinkedListImplementationByAnurag.java for a Pull Request. I hope you understand this.

**Comment by Anurag127001** [comment]
> @Anurag127001 It appears that you are pushing more files, which is not a good practice for adding to a repository. You can add those files in .gitignore causes git to ignore those files. Simply push LinkedListImplementationByAnurag.java for a Pull Request. I hope you understand this.

should i create new branch or create LinkedListImplementationByAnurag.java in main branch and pull request?

**Comment by indrakishore** [comment]
> > @Anurag127001 It appears that you are pushing more files, which is not a good practice for adding to a repository. You can add those files in .gitignore causes git to ignore those files. Simply push LinkedListImplementationByAnurag.java for a Pull Request. I hope you understand this.
> 
> should i create new branch or create LinkedListImplementationByAnurag.java in main branch and pull request?

No need to create another branch just add your file in main branch and create pull request.

**Pull request closed without merging**
