### PR TITLE
merge sort java.

### PR DESCRIPTION
**Pull request by PradeepFSTdhane123**
# Merge sort DSA sorting in java added..

### CODE REVIEW

**Comment by indrakishore** [comment]
> # Merge sort DSA sorting in java added..
> ## -The code effectively implements the Merge Sort algorithm using recursion to divide the array and a helper function to merge the sorted sub-arrays.

@PradeepFSTdhane123 Please add problem statement and approach for every code files.

**Comment by PradeepFSTdhane123** [comment]
@indrakishore { Please add problem statement and approach for every code files.}- problem statement and approach added in file kindely view it ,merge it and lable it . pull request #127, #125

**Comment by PradeepFSTdhane123** [comment]
done

**Comment by PradeepFSTdhane123** [comment]
please merge radix sort sorting algorithm pr

**Pull request merged**
