### PR TITLE
Create MergekSortedListsByKrishna.java

### PR DESCRIPTION
**Pull request by krishna1584**
**Problem Statement:**

Given an array of k sorted linked lists, merge them into one sorted linked list. If the input list is empty or contains only empty lists, return null.

**Example:**

Input:
lists = [[1->4->5], [1->3->4], [2->6]]

Output:
[1->1->2->3->4->4->5->6]

**Approach:**

Divide and Conquer: Recursively divide the array of linked lists into two halves and merge them.
Merge Two Lists: Use a helper function to merge two sorted linked lists by comparing node values.
Time Complexity: O(n log k), where n is the total number of nodes and k is the number of linked lists.
Space Complexity: O(log k) due to recursion depth.
Steps:
If lists is empty, return null.
Recursively merge linked lists using the helper mergeKListsHelper.
Use the merge function to merge two lists by comparing nodes one by one.

This approach efficiently merges k lists with minimal time complexity.

### CODE REVIEW

**Comment by indrakishore** [comment]
> Added a DSA Question and solution for the same in JAVA

@krishna1584 please add problem statement and approach for this file also rename file as protocol.

**Comment by indrakishore** [comment]
> > Added a DSA Question and solution for the same in JAVA
> 
> @krishna1584 please add problem statement and approach for this file also rename file as protocol.

@krishna1584 problem statement and approach is still missing.

**Comment by krishna1584** [comment]
Added problem statement and approach

**Comment by krishna1584** [comment]
I hope this message finds you well. I wanted to inform you that I have created a program to merge K sorted lists in Java and added it to the repository as part of my initial contributions for Hacktoberfest. I have included the problem statement and approach for the solution as told by you.
I would like to request you to add the Hacktoberfest label and merge it. Please let me know if you have any feedback or require any further modifications.

**Comment by krishna1584** [comment]
@indrakishore please merge my PR

**Pull request merged**
