### PR TITLE
FindSecondMaximumByAnurag.java

### PR DESCRIPTION
**Pull request by Anurag127001**
FindSecondMaximumByAnurag.java are added in DSA folder as mentioned in issue https://github.com/indrakishore/Developers-Community/issues/1

Problem Statement : find second maximum value in given array

Approach :

We will take two variables "max" and "secondmax" and assign them lowest integer value ---> Integer.MIN_VALUE

Then we will start comparing elements of array

if arr[i] > max then we will assign 
     secondmax = max
     max  = arr[i]

if arr[i] < max but arr[i] > secondmax
    then we will assign
     secondmax = arr[i]

### CODE REVIEW

**Comment by indrakishore** [comment]
> FindSecondMaximumByAnurag.java are added in DSA folder as mentioned in issue #1
> 
> Problem Statement : find second maximum value in given array
> 
> Approach :
> 
> We will take two variables "max" and "secondmax" and assign them lowest integer value ---> Integer.MIN_VALUE
> 
> Then we will start comparing elements of array
> 
> if arr[i] > max then we will assign secondmax = max max = arr[i]
> 
> if arr[i] < max but arr[i] > secondmax then we will assign secondmax = arr[i]

@Anurag127001 add this problem statement in code file using multiline comments.

**Comment by Anurag0git** [comment]
> > FindSecondMaximumByAnurag.java are added in DSA folder as mentioned in issue #1
> > Problem Statement : find second maximum value in given array
> > Approach :
> > We will take two variables "max" and "secondmax" and assign them lowest integer value ---> Integer.MIN_VALUE
> > Then we will start comparing elements of array
> > if arr[i] > max then we will assign secondmax = max max = arr[i]
> > if arr[i] < max but arr[i] > secondmax then we will assign secondmax = arr[i]
> 
> @Anurag127001 add this problem statement in code file using multiline comments.

sir, my this account has blocked, since i pull requested som issue which were not opened in other repos, so i will be contributing through my new account @Anurag0git

**Comment by indrakishore** [comment]
> > > FindSecondMaximumByAnurag.java are added in DSA folder as mentioned in issue #1
> > > Problem Statement : find second maximum value in given array
> > > Approach :
> > > We will take two variables "max" and "secondmax" and assign them lowest integer value ---> Integer.MIN_VALUE
> > > Then we will start comparing elements of array
> > > if arr[i] > max then we will assign secondmax = max max = arr[i]
> > > if arr[i] < max but arr[i] > secondmax then we will assign secondmax = arr[i]
> > 
> > 
> > @Anurag127001 add this problem statement in code file using multiline comments.
> 
> sir, my this account has blocked, since i pull requested som issue which were not opened in other repos, so i will be contributing through my new account @Anurag0git

ok, no problem.

**Comment by Anurag0git** [comment]
> > > > FindSecondMaximumByAnurag.java are added in DSA folder as mentioned in issue #1
> > > > Problem Statement : find second maximum value in given array
> > > > Approach :
> > > > We will take two variables "max" and "secondmax" and assign them lowest integer value ---> Integer.MIN_VALUE
> > > > Then we will start comparing elements of array
> > > > if arr[i] > max then we will assign secondmax = max max = arr[i]
> > > > if arr[i] < max but arr[i] > secondmax then we will assign secondmax = arr[i]
> > > 
> > > 
> > > @Anurag127001 add this problem statement in code file using multiline comments.
> > 
> > 
> > sir, my this account has blocked, since i pull requested som issue which were not opened in other repos, so i will be contributing through my new account @Anurag0git
> 
> ok, no problem.

please dont accept this pull request, i will add new file with same PS

**Comment by indrakishore** [comment]
> > > > > FindSecondMaximumByAnurag.java are added in DSA folder as mentioned in issue #1
> > > > > Problem Statement : find second maximum value in given array
> > > > > Approach :
> > > > > We will take two variables "max" and "secondmax" and assign them lowest integer value ---> Integer.MIN_VALUE
> > > > > Then we will start comparing elements of array
> > > > > if arr[i] > max then we will assign secondmax = max max = arr[i]
> > > > > if arr[i] < max but arr[i] > secondmax then we will assign secondmax = arr[i]
> > > > 
> > > > 
> > > > @Anurag127001 add this problem statement in code file using multiline comments.
> > > 
> > > 
> > > sir, my this account has blocked, since i pull requested som issue which were not opened in other repos, so i will be contributing through my new account @Anurag0git
> > 
> > 
> > ok, no problem.
> 
> please dont accept this pull request, i will add new file with same PS

Sure, Closing this PR.

**Pull request closed without merging**
