### PR TITLE
Created 0-1knapsack in java

### PR DESCRIPTION
**Pull request by DhruvTotala**
The provided Java program implements the 0-1 Knapsack problem using dynamic programming to determine the maximum value that can be obtained with a given capacity. It defines a knapsack function that constructs a 2D array to track the maximum values for subsets of items based on their weights and values. The user is prompted to input the number of items, their respective weights and values, and the knapsack's capacity. After processing the inputs, the program calculates and outputs the maximum value achievable within the specified capacity. This approach efficiently solves the problem by building on previously computed results.

### CODE REVIEW

**Comment by DhruvTotala** [comment]
@indrakishore please review this code

**Comment by indrakishore** [comment]
> The provided Java program implements the 0-1 Knapsack problem using dynamic programming to determine the maximum value that can be obtained with a given capacity. It defines a knapsack function that constructs a 2D array to track the maximum values for subsets of items based on their weights and values. The user is prompted to input the number of items, their respective weights and values, and the knapsack's capacity. After processing the inputs, the program calculates and outputs the maximum value achievable within the specified capacity. This approach efficiently solves the problem by building on previously computed results.

@DhruvTotala Please add problem statement and approach in the code file.

**Comment by indrakishore** [comment]
> > The provided Java program implements the 0-1 Knapsack problem using dynamic programming to determine the maximum value that can be obtained with a given capacity. It defines a knapsack function that constructs a 2D array to track the maximum values for subsets of items based on their weights and values. The user is prompted to input the number of items, their respective weights and values, and the knapsack's capacity. After processing the inputs, the program calculates and outputs the maximum value achievable within the specified capacity. This approach efficiently solves the problem by building on previously computed results.
> 
> @DhruvTotala Please add problem statement and approach in the code file.

Please do it asap.

**Review by DhruvTotala — COMMENTED** [review]
I have made necessary changes.

**Pull request merged**
